apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
resources:
  - namespace.yaml
  - https://github.com/cert-manager/cert-manager/releases/download/v1.8.2/cert-manager.crds.yaml
  - repository.yaml
  - release.yaml
  - issuer-lets-encrypt-staging.yaml
  - issuer-lets-encrypt-production.yaml
