apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  interval: 5m
  chart:
    spec:
      version: "v1.8.2"
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack
      interval: 60m
  # Manually installing CRDs using url
  install:
    crds: Skip
  upgrade:
    crds: Skip
  # https://artifacthub.io/packages/helm/cert-manager/cert-manager
  values: { }
