{
 "title": "FullNodes",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  {
   "title": "State Sync",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "State Sync Lag",
   "type": "graph",
   "description": "Ledger timestamp's lag compared to the nodes current time.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "(diem_state_sync_timestamp{type=\"real\", job=~\"$job\"} - on (instance, job) diem_state_sync_timestamp{type=\"synced\", job=~\"$job\"})",
     "legendFormat": "{{job}} - {{instance}}"
    }
   ]
  },
  {
   "title": "State Sync Version",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "diem_state_sync_version{type=\"committed\", job=~\"$job\"}",
     "legendFormat": "{{job}} - {{instance}} - committed"
    },
    {
     "expr": "diem_state_sync_version{type=\"synced\", job=~\"$job\"}",
     "legendFormat": "{{job}} - {{instance}} -  synced"
    }
   ]
  },
  {
   "title": "State Sync Rate",
   "type": "graph",
   "description": "Rate at which the synced version is increasing",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "/s" }
   ],
   "targets": [
    {
     "expr": "rate(diem_state_sync_version{type=\"synced\", job=~\"$job\"}[5m])",
     "legendFormat": "{{job}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Synchronized",
   "type": "graph",
   "description": "1 = It's fully synchronized\n0 = It's NOT synchronized",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(diem_state_sync_version{type=\"highest\", job=~\"$job\"} - on(instance, job) diem_state_sync_version{type=\"committed\", job=~\"$job\"}) < bool 15",
     "legendFormat": "{{job}} - {{instance}}"
    }
   ]
  },
  {
   "title": "State Sync Epoch",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "diem_state_sync_epoch{job=~\"$job\"}",
     "legendFormat": "{{job}} - {{instance}}"
    }
   ]
  },
  {
   "title": "State Sync Upstream Peers",
   "type": "graph",
   "description": "Number of upstream peers that can provide up to date information about the ledger.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(diem_state_sync_active_upstream_peers{job=~\"$job\"}) by (instance, job) ",
     "legendFormat": "{{job}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Mempool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Mempool Pending transactions",
   "type": "graph",
   "description": "Number of uncommitted but still valid (not expired nor discarded) transactions in the nodes Mempool.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "diem_core_mempool_index_size{index=\"system_ttl\", job=~\"$job\"}",
     "legendFormat": "{{job}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Mempool Txn Commit Latency",
   "type": "graph",
   "description": "The time between Mempool receiving the transaction and time to be committed. Note: due to reliability mechanisms, this value can be lower than it really is.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "diem_core_mempool_txn_commit_latency_sum{job=~\"$job\"} / diem_core_mempool_txn_commit_latency_count{job=~\"$job\"}",
     "legendFormat": "{{job}} - {{instance}} - {{stage}}"
    }
   ]
  },
  {
   "title": "Networking",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Network Connections (Incoming)",
   "type": "graph",
   "description": "Number of Inbound Connections as measured by DiemNet",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "diem_connections{direction=\"inbound\",network_id=\"Public\"}",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Network Connections (Outgoing)",
   "type": "graph",
   "description": "Number of  Outbound Network Connections as measured by DiemNet",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "diem_connections{direction=\"outbound\",network_id=\"Public\"}",
     "legendFormat": "{{peer_id}}"
    }
   ]
  }
 ]
}