{
 "title": "Validator",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  { "title": "Validator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Consensus Rounds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "diem_consensus_current_round{job=~\"$job\"}",
     "legendFormat": "{{job}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Committed Blocks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "diem_consensus_last_committed_round{job=~\"$job\"}",
     "legendFormat": "{{job}} - {{instance}}"
    }
   ]
  },
  {
   "title": "State Sync Committed & Synced Version",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "diem_state_sync_version{type=\"committed\", job=~\"$job\"}",
     "legendFormat": "{{job}} - {{instance}} - committed"
    },
    {
     "expr": "diem_state_sync_version{type=\"synced\", job=~\"$job\"}",
     "legendFormat": "{{job}} - {{instance}} - synced"
    }
   ]
  },
  {
   "title": "Mempool Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "diem_core_mempool_index_size{index=\"system_ttl\", job=~\"$job\"}",
     "legendFormat": "{{job}} - {{instance}}"
    }
   ]
  },
  {
   "title": "E2E Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(diem_core_mempool_txn_commit_latency_sum{stage=~\"commit_accepted|commit_rejected\", job=~\"$job\"}[$__rate_interval])/rate(diem_core_mempool_txn_commit_latency_count{stage=~\"commit_accepted|commit_rejected\", job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{job}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Committed blocks per sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(diem_consensus_last_committed_round{job=~\"$job\"}[5m])",
     "legendFormat": "{{job}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Block creation to signed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(diem_consensus_block_tracing_sum{stage=\"signed\", job=~\"$job\"}[5m]) / rate(diem_consensus_block_tracing_count{stage=\"signed\", job=~\"$job\"}[5m])",
     "legendFormat": "{{job}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Committed successful txns per sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(diem_consensus_last_committed_version{job=~\"$job\"}[5m])",
     "legendFormat": "{{job}} - {{instance}}"
    }
   ]
  }
 ]
}