{
 "title": "VM",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "owner", "query": { "query": "label_values(owner)" } },
   { "name": "role", "query": { "query": "label_values(role)" } },
   {
    "name": "interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "job", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  {
   "title": "General Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "User Transactions (Successful)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "none", "label": "transactions/s" }
   ],
   "targets": [
    {
     "expr": "rate(diem_vm_user_transactions_executed{status=\"success\", job=~\"$job\"}[$interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "System Transactions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "none", "label": "transactions/s" }
   ],
   "targets": [
    {
     "expr": "rate(diem_vm_system_transactions_executed{job=~\"$job\"}[$interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Validated Transactions (Successful)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none", "label": "transactions/s" }
   ],
   "targets": [
    {
     "expr": "rate(diem_vm_transactions_validated{status=\"success\", job=~\"$job\"}[$interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Num Txns per Block",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "none", "label": "txns per block" }
   ],
   "targets": [
    {
     "expr": "rate(diem_vm_num_txns_per_block_sum{job=~\"$job\"}[$interval]) / rate(diem_vm_num_txns_per_block_count{job=~\"$job\"}[$interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Gas Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Avg Gas per User Txn",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "none", "label": "gas/txn" }
   ],
   "targets": [
    {
     "expr": "rate(diem_vm_txn_gas_usage_sum{job=~\"$job\"}[$interval]) / rate(diem_vm_txn_gas_usage_count{job=~\"$job\"}[$interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Avg Txn Total Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(diem_vm_txn_total_seconds_sum{job=~\"$job\"}[$interval]) / rate(diem_vm_txn_total_seconds_count{job=~\"$job\"}[$interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Avg Txn Validation Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(diem_vm_txn_validation_seconds_sum{job=~\"$job\"}[$interval])/rate(diem_vm_txn_validation_seconds_count{job=~\"$job\"}[$interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Avg Time per Gas Unit",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "s", "label": "seconds / unit gas" }
   ],
   "targets": [
    {
     "expr": "rate(diem_vm_txn_total_seconds_sum{job=~\"$job\"}[$interval])/rate(diem_vm_txn_total_seconds_count{job=~\"$job\"}[$interval])/(rate(diem_vm_txn_gas_usage_sum{job=~\"$job\"}[$interval])/rate(diem_vm_txn_gas_usage_count{job=~\"$job\"}[$interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}