{
 "title": "Overview",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "owner", "query": { "query": "label_values(owner)" } },
   { "name": "job", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  {
   "title": "Validators",
   "type": "geomap",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "queryText": "SELECT validator_lat AS latitude, validator_lon AS longitude, account, validator_ip FROM validators_geo_data WHERE timestamp = (SELECT MAX(timestamp) FROM validators_geo_data)\n",
     "rawQueryText": "SELECT validator_lat AS latitude, validator_lon AS longitude, account, validator_ip FROM validators_geo_data WHERE timestamp = (SELECT MAX(timestamp) FROM validators_geo_data)\n"
    }
   ]
  },
  {
   "title": "VFNs",
   "type": "geomap",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "queryText": "SELECT vfn_lat AS latitude, vfn_lon AS longitude, account, vfn_ip FROM validators_geo_data WHERE timestamp = (SELECT MAX(timestamp) FROM validators_geo_data)",
     "rawQueryText": "SELECT vfn_lat AS latitude, vfn_lon AS longitude, account, vfn_ip FROM validators_geo_data WHERE timestamp = (SELECT MAX(timestamp) FROM validators_geo_data)"
    }
   ]
  },
  {
   "title": "Network Status",
   "type": "timeseries",
   "description": "Total committed rounds averaged on 10 minutes",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum(rate(diem_consensus_last_committed_round[10m]) < 100)",
     "legendFormat": "Total committed rounds"
    },
    { "expression": "$A >= 1", "type": "math" },
    { "expression": "$A < 1", "type": "math" }
   ]
  },
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "ValidatorSet",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 2, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "quantile(0.67, diem_consensus_current_epoch_validators)"
      }
     ]
    },
    {
     "title": "Down node %",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 5, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "1 - (count(rate(diem_consensus_current_round[10m]) > 0) OR on() vector(0)) / quantile(0.67, diem_consensus_current_epoch_validators)"
      }
     ]
    },
    {
     "title": "Not reporting metrics",
     "type": "table",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 14 },
     "targets": [
      {
       "expr": "up{job=\"federate\"} == 0 or up{job=\"diem-procs\", role=\"validator\"} == 0"
      }
     ]
    },
    {
     "title": "Not Participating Consensus",
     "type": "table",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 14 },
     "targets": [
      {
       "expr": "rate(diem_consensus_last_committed_round{role=\"validator\"}[1m]) == 0 OR vector(0)"
      }
     ]
    }
   ]
  },
  {
   "title": "SLA",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Validator Uptime SLA",
     "type": "graph",
     "description": "Average uptime for 30 days.",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(commit_uptime{job=~\"$job\"}[30d])",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Validator Participation SLA",
     "type": "graph",
     "description": "Average participation uptime for 30 days. A node is required to propose at least one block every 12 hours to be counted as up.",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 15 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(proposal_uptime{job=~\"$job\"}[30d])",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Fullnode Uptime SLA",
     "type": "graph",
     "description": "Average fullnode uptime for 30 days. A fully synchronized fullnode is counted as up.",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 15 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(fullnode_uptime{job=~\"$job\"}[30d])",
       "legendFormat": "{{job}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Validator health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Validator Connected Peers",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "expr": "sum by (job)(diem_connections{network_id=\"Validator\", role_type=\"validator\", job=~\"$job\"})",
       "legendFormat": "{{owner}}"
      }
     ]
    },
    {
     "title": "Committed & Synced Version",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 16 },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "expr": "diem_state_sync_version{type=\"committed\", job=~\"$job\", role=\"validator\"}",
       "legendFormat": "{{job}}-committed"
      },
      {
       "expr": "diem_state_sync_version{type=\"synced\", job=~\"$job\", role=\"validator\"}",
       "legendFormat": "{{job}}-synced"
      }
     ]
    },
    {
     "title": "Committed blocks per sec",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 16 },
     "yaxes": [
      { "format": "short", "label": "blocks per sec" }
     ],
     "targets": [
      {
       "expr": "rate(diem_consensus_last_committed_round{job=~\"$job\"}[1m])",
       "legendFormat": "{{job}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Fullnode health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Fullnode Connected Peers",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "expr": "sum by (job, network_id)(diem_connections{role_type=\"full_node\", job=~\"$job\"})",
       "legendFormat": "{{job}}-{{network_id}}"
      }
     ]
    },
    {
     "title": "Fullnode Upstream Peers",
     "type": "graph",
     "description": "Number of upstream validator peers a full node can proxy transactions up to",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 17 },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "expr": "diem_state_sync_active_upstream_peers{role=\"fullnode\", job=~\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "State synced version",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 17 },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "expr": "diem_state_sync_version{type=\"synced\", role=\"fullnode\", job=~\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Consensus",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Error Rate",
     "type": "graph",
     "description": "The error rate of main loop.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(diem_consensus_error_count{job=~\"$job\"}[1m]) / on (job) rate(consensus_duration_count{op='main_loop', job=~\"$job\"}[1m])",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Round Timeout Rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(diem_consensus_timeout_rounds_count{job=~\"$job\"}[1m])",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Current Round",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "expr": "diem_consensus_current_round{job=~\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Mempool size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "diem_core_mempool_index_size{index=\"system_ttl\", job=~\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Avg e2e latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(diem_core_mempool_txn_commit_latency_sum{stage=~\"commit_accepted|commit_rejected\", job=~\"$job\"}[1m])/rate(diem_core_mempool_txn_commit_latency_count{stage=~\"commit_accepted|commit_rejected\", job=~\"$job\"}[1m])",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Block execution time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(diem_executor_execute_block_seconds_bucket{role=\"validator\", job=~\"$job\"}[1m])) by (le))",
       "legendFormat": "P99"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(diem_executor_execute_block_seconds_bucket{role=\"validator\", job=~\"$job\"}[1m])) by (le))",
       "legendFormat": "P95"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(diem_executor_execute_block_seconds_bucket{role=\"validator\", job=~\"$job\"}[1m])) by (le))",
       "legendFormat": "P50"
      }
     ]
    }
   ]
  },
  {
   "title": "Keys",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Key Manager: Keys Still Fresh (Last Hour)",
     "type": "graph",
     "description": "This panel tracks whether the key manager successfully ran within the last hour and determined if the keys are still fresh. If so, the key manager is healthy and 1 is displayed, otherwise, the key manager is unhealthy and 0 is displayed.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
     "yaxes": [
      {
       "format": "short",
       "label": "Keys Still Fresh? (Bool, 1= Yes, 0 = No)"
      }
     ],
     "targets": [
      {
       "expr": "increase(diem_key_manager_state{state=\"keys_still_fresh\", job=~\"$job\"}[1h]) > bool 1",
       "legendFormat": "{{job}}"
      }
     ]
    }
   ]
  }
 ]
}