apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - namespace.yaml
  - repository.yaml
  - release.yaml
  - grafana/pvc.yaml
  - grafana/geo/geo.cronjob.yaml

configMapGenerator:
  - name: geo-cron-main-python
    files:
      - main.py=grafana/geo/main.py

secretGenerator:
  - name: prometheus-basic-auth
    files:
      - auth=prometheus.auth.htpasswd
    options:
      disableNameSuffixHash: true
