{
 "title": "0L Node",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Active Validators",
    "query": {}
   },
   {
    "name": "ol_node_type",
    "label": "Node Type",
    "query": "Validator : validator, VFN : vfn, Fullnode : fullnode"
   },
   {
    "name": "interval",
    "label": "Aggregation interval",
    "query": "15s,30s,1m,5m,10m,15m,30m,1h,2h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "discord_ex", "label": "Exclude Discord Regex", "query": "zmanian.+" },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Validators Only", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Mempool Size",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "diem_core_mempool_index_size{index=\"system_ttl\", job=~\"$job\", ol_ignore=\"\"}",
     "legendFormat": "id-{{job}}-id @{{ol_discord}}"
    }
   ]
  },
  {
   "title": "Committed blocks per sec ($interval)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 10, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(diem_consensus_last_committed_round{job=~\"$job\", ol_ignore=\"\"}[$interval]) < 5",
     "legendFormat": "id-{{job}}-id @{{ol_discord}}"
    }
   ]
  },
  {
   "title": "Block creation to commit ($interval)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 10, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(\nrate(diem_consensus_block_tracing_sum{job=~\"$job\", stage=\"committed\", ol_ignore=\"\"}[$interval])\n/\nrate(diem_consensus_block_tracing_count{job=~\"$job\", stage=\"committed\", ol_ignore=\"\"}[$interval])\n) < 50",
     "legendFormat": "id-{{job}}-id @{{ol_discord}}"
    }
   ]
  },
  {
   "title": "New Rounds / minute per validator ($interval)",
   "type": "timeseries",
   "description": "How many new rounds are being synced per minute",
   "gridPos": { "h": 18, "w": 18, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "rate(diem_consensus_current_round{job=~\"$job\", ol_ignore=\"\"}[$interval])*60 < 200",
     "legendFormat": "id-{{job}}-id @{{ol_discord}}"
    }
   ]
  },
  {
   "title": "Round per validator",
   "type": "table",
   "gridPos": { "h": 18, "w": 6, "x": 18, "y": 14 },
   "targets": [
    {
     "expr": "(diem_consensus_current_round{ol_ignore=\"\"})",
     "legendFormat": "{{6}}ss"
    },
    {
     "expr": "(diem_consensus_last_committed_round{ol_ignore=\"\"})",
     "legendFormat": "{{6}}ss"
    }
   ]
  },
  {
   "title": "Committed votes per window",
   "type": "timeseries",
   "description": "Total number of validator's committed votes in the current reputation window",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(diem_committed_votes_in_window{job=~\"$job\", ol_ignore=\"\"})",
     "legendFormat": "id-{{job}}-id @{{ol_discord}}"
    }
   ]
  },
  {
   "title": "Total Committed props per window",
   "type": "timeseries",
   "description": "Total number of validator's committed proposals in the current reputation window",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "diem_committed_proposals_in_window{job=~\"$job\", ol_ignore=\"\"}",
     "legendFormat": "id-{{job}}-id @{{ol_discord}}"
    }
   ]
  },
  { "title": "Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "State Sync Committed & Synced Version",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "diem_state_sync_version{type=\"committed\", job=~\"$job\", ol_node_type=~\"$ol_node_type\", ol_ignore=\"\"}",
     "legendFormat": "id-{{job}}-id ({{ol_node_type}}) committed @{{ol_discord}}"
    },
    {
     "expr": "diem_state_sync_version{type=\"synced\", job=~\"$job\", ol_node_type=~\"$ol_node_type\", ol_discord!~\"$discord_ex\"}",
     "legendFormat": "id-{{job}}-id ({{ol_node_type}}) synced @{{ol_discord}}"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "RAM Used",
   "type": "timeseries",
   "description": "Non available RAM memory",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 \n- (\n    (node_memory_MemAvailable_bytes{job=~\"$job\", ol_node_type=~\"$ol_node_type\", ol_ignore=\"\"} * 100) / \n    node_memory_MemTotal_bytes{job=~\"$job\", ol_node_type=~\"$ol_node_type\", ol_ignore=\"\"}\n)",
     "legendFormat": "id-{{job}}-id {{ol_node_type}} @{{ol_discord}}"
    }
   ]
  },
  {
   "title": "CPU Used ($interval)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (job,ol_node_type,ol_discord) (rate(node_cpu_seconds_total{mode=\"idle\", job=~\"$job\", ol_node_type=~\"$ol_node_type\", ol_ignore=\"\"}[$interval])) * 100)",
     "legendFormat": "id-{{job}}-id {{ol_node_type}} @{{ol_discord}}"
    }
   ]
  },
  {
   "title": "WIP...",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current Round per validator",
     "type": "bargauge",
     "gridPos": { "h": 18, "w": 15, "x": 3, "y": 71 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "(diem_consensus_current_round{ol_ignore=\"\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}